[package]
name = "boltzmann"
version = "0.1.0"
authors = ["hargados <hargados@tcd.ie>"]

[dependencies]

rand = "0.3"
glutin = "0.7.1"
glium = "*"
toml = "0.2.1"
rustc-serialize = "0.3.22"
scoped-pool = "1"
